on: pull_request

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
      DB_HOST: localhost
      DB_PORT: 5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: List directory contents
        run: ls -la

      - name: Run tests
        run: pytest -v
