on: pull_request

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: meu_usuario
          POSTGRES_PASSWORD: minha_senha
          POSTGRES_DB: meu_banco

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Wait for PostgreSQL to start
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done

      - name: Run tests
        env:
          POSTGRES_USER: meu_usuario
          POSTGRES_PASSWORD: minha_senha
          POSTGRES_DB: meu_banco
          DB_HOST: localhost
          DB_PORT: 5432
        run: pytest -v
